In [22]:
import seaborn as sns
import matplotlib.pyplot as plt

import pandas as pd

# *Dataset: Student Alcohol Consumption*

Os dados foram obtidos por meio de uma pesquisa com estudantes do ensino secundário que cursavam Matemática e Língua Portuguesa. O conjunto de dados contém diversas **informações sobre os aspectos sociais, o gênero e os hábitos de estudo dos estudantes.**

# *Dicionário*

Atributos presentes nos dois conjuntos de dados: `student-mat.csv` (curso de Matemática) e `student-por.csv` (curso de Língua Portuguesa).

1. escola — Escola do estudante (binária: `'GP'` — Gabriel Pereira ou `'MS'` — Mousinho da Silveira).

2. sexo — Sexo do estudante (binária: `'F'` — feminino ou `'M'` — masculino).

3. idade — Idade do estudante (numérica: de 15 a 22 anos).

4. regiao — Tipo de endereço residencial do estudante (binária: `'U'` — urbano ou `'R'` — rural).

5. tamanho_familia — Tamanho da família (binária: `'LE3'` — menor ou igual a 3 pessoas ou `'GT3'` — maior que 3 pessoas).

6. convivencia_pais — Situação de convivência dos pais (binária: `'T'` — moram juntos ou `'A'` — moram separados).

7. educacao_mae — Escolaridade da mãe (numérica: 0 — nenhuma; 1 — ensino primário, equivalente à 4ª série; 2 — do 5º ao 9º ano; 3 — ensino secundário; ou 4 — ensino superior).

8. educacao_pai — Escolaridade do pai (numérica: 0 — nenhuma; 1 — ensino primário, equivalente à 4ª série; 2 — do 5º ao 9º ano; 3 — ensino secundário; ou 4 — ensino superior).

9. trabalho_mae — Profissão da mãe (categórica nominal: `'teacher'` — professora; `'health'` — área da saúde; `'services'` — serviços públicos, como administração ou polícia; `'at_home'` — trabalha em casa; ou `'other'` — outra profissão).

10. trabalho_pai — Profissão do pai (categórica nominal: `'teacher'` — professor; `'health'` — área da saúde; `'services'` — serviços públicos, como administração ou polícia; `'at_home'` — trabalha em casa; ou `'other'` — outra profissão).

11. escolha_escola — Motivo para escolher a escola (categórica nominal: proximidade de `'home'` — casa; reputação da escola (`'reputation'`); preferência pelo curso (`'course'`); ou outro motivo (`'other'`)).

12. guardiao_legal — Responsável legal pelo estudante (categórica nominal: `'mother'` — mãe; `'father'` — pai; ou `'other'` — outro).

13. tempo_viagem_escola — Tempo de deslocamento de casa até a escola (numérica: 1 — menos de 15 minutos; 2 — de 15 a 30 minutos; 3 — de 30 minutos a 1 hora; ou 4 — mais de 1 hora).

14. tempo_estudo_semanal — Tempo semanal de estudo (numérica: 1 — menos de 2 horas; 2 — de 2 a 5 horas; 3 — de 5 a 10 horas; ou 4 — mais de 10 horas).

15. nº_reprovacoes — Número de reprovações anteriores (numérica: indica o número de reprovações quando 1≤n<31 \leq n < 31≤n<3; caso contrário, o valor é 4).

16. apoio_escola — Recebe apoio educacional extra da escola (binária: sim ou não).

17. apoio_familiar — Recebe apoio educacional da família (binária: sim ou não).

18. paid — Participa de aulas particulares pagas na disciplina correspondente (Matemática ou Língua Portuguesa) (binária: sim ou não).

19. participacao_atividades_extras — Participa de atividades extracurriculares (binária: sim ou não).

20. edu_infantil — Frequentou a educação infantil (binária: sim ou não).

21. desejo_de_ensino superior — Deseja cursar o ensino superior (binária: sim ou não).

22. acesso_internet_casa — Possui acesso à internet em casa (binária: sim ou não).

23. relacionamento_amoroso — Está em um relacionamento amoroso (binária: sim ou não).

24. qualidade_relacao_familiar — Qualidade das relações familiares (numérica: de 1 — muito ruim a 5 — excelente).

25. tempo_livre — Tempo livre após as aulas (numérica: de 1 — muito baixo a 5 — muito alto).

26. frequencia_saida_com_amigos — Frequência com que sai com os amigos (numérica: de 1 — muito baixa a 5 — muito alta).

27. consumo_alcool_semana — Consumo de álcool durante os dias úteis (numérica: de 1 — muito baixo a 5 — muito alto).

28. consumo_alcool_fim_de_semana — Consumo de álcool durante os fins de semana (numérica: de 1 — muito baixo a 5 — muito alto).

29. estado_saude_atual — Estado de saúde atual (numérica: de 1 — muito ruim a 5 — muito bom).

30. faltas — Número de faltas escolares (numérica: de 0 a 93).

31. nota_1p — Nota do primeiro período (numérica: de 0 a 20).

32. nota_2p — Nota do segundo período (numérica: de 0 a 20).

33. nota_final — Nota final (numérica: de 0 a 20; variável-alvo para previsão).

In [23]:
d1 = pd.read_csv('files/student-por.csv')

display(d1)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,MS,F,19,R,GT3,T,2,3,services,other,...,5,4,2,1,2,5,4,10,11,10
645,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,3,4,1,1,1,4,15,15,16
646,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,1,5,6,11,12,9
647,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,6,10,10,10
648,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,4,10,11,11

In [24]:
# Retirando algumas colunas.
d1 = d1.drop(columns=['school', 'Medu', 'Fedu', 'Mjob', 'Fjob', 'reason', 'traveltime', 'schoolsup', 'paid', 'nursery'])

# Renomeando as colunas sobrantes:
d1 = d1.rename(columns={
    'sex': 'sexo',
    'age': 'idade',
    'address': 'regiao',
    'absences': 'faltas',
    'famsize': 'tamanho_familia',
    'Pstatus': 'convivencia_pais',
    'guardian': 'guardiao_legal',
    'studytime': 'tempo_semanal_estudo',
    'failures': 'nº_reprovacoes',
    'famsup': 'apoio_familiar',
    'activities': 'participacao_atividades_extras',
    'higher': 'desejo_de_ensino superior',
    'internet': 'acesso_internet_casa',
    'romantic': 'relacionamento_amoroso',
    'famrel': 'qualidade_relacao_familiar',
    'freetime': 'tempo_livre',
    'goout': 'frequencia_saida_com_amigos',
    'Dalc': 'consumo_alcool_semana',
    'Walc': 'consumo_alcool_fim_de_semana',
    'health': 'estado_saude_atual',
    'G1': 'nota_1p',
    'G2': 'nota_2p',
    'G3': 'nota_final'
})

# Printando d1:

display(d1)

print(d1.isnull().sum())
# não tem nulos

print("Duplicatas:", d1.duplicated().sum())
# não tem duplicatas

,sexo,idade,regiao,tamanho_familia,convivencia_pais,guardiao_legal,tempo_semanal_estudo,nº_reprovacoes,apoio_familiar,participacao_atividades_extras,...,qualidade_relacao_familiar,tempo_livre,frequencia_saida_com_amigos,consumo_alcool_semana,consumo_alcool_fim_de_semana,estado_saude_atual,faltas,nota_1p,nota_2p,nota_final
0,F,18,U,GT3,A,mother,2,0,no,no,...,4,3,4,1,1,3,4,0,11,11
1,F,17,U,GT3,T,father,2,0,yes,no,...,5,3,3,1,1,3,2,9,11,11
2,F,15,U,LE3,T,mother,2,0,no,no,...,4,3,2,2,3,3,6,12,13,12
3,F,15,U,GT3,T,mother,3,0,yes,yes,...,3,2,2,1,1,5,0,14,14,14
4,F,16,U,GT3,T,father,2,0,yes,no,...,4,3,2,1,2,5,0,11,13,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,F,19,R,GT3,T,mother,3,1,no,yes,...,5,4,2,1,2,5,4,10,11,10
645,F,18,U,LE3,T,mother,2,0,yes,no,...,4,3,4,1,1,1,4,15,15,16
646,F,18,U,GT3,T,mother,2,0,no,yes,...,1,1,1,1,1,5,6,11,12,9
647,M,17,U,LE3,T,mother,1,0,no,no,...,2,4,5,3,4,2,6,10,10,10
648,M,18,R,LE3,T,mother,1,0,no,no,...,4,4,1,3,4,5,4,10,11,11

sexo                              0
idade                             0
regiao                            0
tamanho_familia                   0
convivencia_pais                  0
guardiao_legal                    0
tempo_semanal_estudo              0
nº_reprovacoes                    0
apoio_familiar                    0
participacao_atividades_extras    0
desejo_de_ensino superior         0
acesso_internet_casa              0
relacionamento_amoroso            0
qualidade_relacao_familiar        0
tempo_livre                       0
frequencia_saida_com_amigos       0
consumo_alcool_semana             0
consumo_alcool_fim_de_semana      0
estado_saude_atual                0
faltas                            0
nota_1p                           0
nota_2p                           0
nota_final                        0
dtype: int64
Duplicatas: 0